
credentials:
  usernames:
    admin:
      email: admin@crypto.io
      name: Admin
      password: '$2b$12$7MSS6cyPfqKLyzjeVS16HOz4Uw7e8AzJYpZgD85zTxov8BhLBTHXy'  # password = 'btcalt2025'
cookie:
  name: crypto_dashboard_cookie
  key: some_random_key
  expiry_days: 30
