credentials:
  usernames:
    admin:
      email: admin@crypto.io
      name: Admin
      password: 'alt2024btc!'  # <-- PAS de hash ici
cookie:
  name: crypto_dashboard_cookie
  key: some_random_key
  expiry_days: 30
